### ISSUE TITLE
Game should switch to ncurses for terminal display/rendering

### ISSUE THREAD

**Issue by nyanpasu** [tupini07/RubyMan#1]
Just a suggestion.

**Comment by shved** [comment]
I've just tried to touch this project to have some basic Ruby practice and it turned out that it works only with win32 platform, while I'm using Mac. Is switch to ncurses means that it will work for all terminals independently from launch platform?

**Comment by tupini07** [comment]
Well it will at least work with every platform that has the ruby ncurses library .. I'm using Ubuntu and the project works fine for me. Which version of ruby are you using? What is the problem that you are getting when you execute `ruby main.rb` from your terminal?

**Comment by shved** [comment]
When I execute `ruby main.rb` it fails to load dependencies at first. So I installed colorize gem and then tried to install win32console gem with `sudo gem install win32console`, but it thrown an error:
```
compiling Console.c
Console.c:1:10: fatal error: 'windows.h' file not found
#include <windows.h>
         ^
1 error generated.
```
Also README.txt of win32console says: 
https://github.com/luislavena/win32console/blob/49ec9177bf08deb32bdfdb9c9c74fa8c5db23ad9/README.txt#L18

I concluded that it works only for windows. So surprisingly it also works on Ubuntu.

BTW: I'd make a Gemfile for this repo to manage dependencies with `bundle install`

**Comment by tupini07** [comment]
ok, I looked a little bit deeper in the problem. The 'win32console' gem was included for compatibility between the Unix terminal and the windows console, in other words, it was used to 'play' the game on both platforms. However, since Ruby 2.0 there is official support for unicode characters output and ANSI escape secuences (which where kind of buggy in previous releases), so I just pushed a commit in which I removed the 'win32console' gem, so now you should have no problems :) just remember to use a Ruby version higher than 2.0.

As for the Gemfile making I really have no idea where to start, maybe you  could do that :) :+1:

**Comment by shved** [comment]
Everything works well now. I use ruby v.2.0.0.

I'll try to set up dependencies management with bundle and Gemfile.

Thanks.

**Comment by tupini07** [comment]
thank you :)

**Comment by tupini07** [comment]
You are very welcome :)
